openapi: 3.0.3
info:
  title: Цифровой Навигатор
  description: Цифровой помощник отсеживающий прогресс публикации проекта от регистрации Руководителя
  version: 1.0.0
paths:

  /user:
    get:
      description: search user in API uri?
      parameters:
        - name: user_uri
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: integer
                description: user ID
    
    post:
      description: Register new user in system, throw exeption if uri is registered
      parameters:
        - name: user_uri
          in: query
          required: true
          schema:
            type: string
            
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: integer
                description: user ID
        400:
          description: uri is registered!
                
    put:
      description: Edit user data
      parameters:
        - name: user_ID
          in: header
          required: true
          schema:
            type: integer
        
        - name: replace_uri
          in: header
          schema:
            type: string
        
      responses:
        200:
          description: OK
  
  /guides/general:
    get:
      description: return general guides list
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/section'
                  
  /guides:
    get:
      description: return general guides list
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/section'
  
components:
  schemas:
    
    user:
      description: an service user
      properties:
        id:
          type: integer
          format: primary_key
        csi_key:
          type: string
          format: primary_key
          uniqueItems: true
    
    section:
      description: guide 'level'
      properties:
        id:
          type: integer
          format: primary_key
        title:
          type: string
        description:
          type: string
        required_sections_id:
          type: array
          items:
            type: integer
        complited_by_user:
          type: boolean
        curent_step:
          type: integer
    
    step:
      description: guide 'step', simple instruction
      properties:
        id:
          type: integer
          format: primary_key
        section_id:
          type: integer
          format: primary_key
        content:
          type: string
          format: json
        complited:
          type: boolean
        